name: Deploy

on:

  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt update
    - name: download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    - name: ekstrak
      run: tar zxvf ngrok-v3-stable-linux-amd64.tgz
    - name: authtoken
      run: ./ngrok authtoken 2MY7zNP4tkQWLRVQfyIVPCUa6vM_7tHLWXqEwW1HNQQYscWQS
    - name: ngrok
      run: ./ngrok http 8000 &
    - name: nnnnnn
      run: npx  --yes gritty --port 8000 --auto-restart
