name: Deploy

on:

  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt update
    - name: download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    - name: ekstrak
      run: tar zxvf ngrok-v3-stable-linux-amd64.tgz
    - name: authtoken
      run: ./ngrok authtoken 2LYdD6efAg3XrBFgxL763JyDDYJ_3VmWuEyXhocdZHwzkkomo
    - name: ngrok
      run: ./ngrok http 6080 &
    - name: snap novnc
      run: wget -O nomachine.tar.gz https://download.nomachine.com/packages/8.4-PRODUCTION/Linux/nomachine-enterprise-desktop_8.4.2_1_x86_64.tar.gz
    - run: tar zxvf nomachine.tar.gz
    - run: sudo NX/nxserver --install
